services:
  proxy:
    build: nginx/
    image: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  backend:
    build: .
    image: backend
    expose:
      - "8000"
    depends_on:
      - db
    secrets:
      - db-password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: example
    volumes:
      - db_data:/var/lib/mysql

    secrets:
      - db-password

secrets:
  db-password:
    file: ./db-password.txt

volumes:
  db_data:
